### ISSUE TITLE
Keine Fehlermeldung wenn maxdb.cfg nicht vorhanden ist

### ISSUE THREAD

**Issue by wemsras** [iteratio-com/Exchange#7]
Hallo,

in der aktuellen Version 1.3.5 erfolgt keine Fehlermeldung wenn die maxdb.cfg Datei nicht vorhanden ist.
```
def parse_config_file()
....
if not config():
=> ergibt immer "OK" da ein config Objekt vorhanden ist.
```
evtl. kann die Abfrage durch 
`if not config.sections():`
ersetzt werden. Dann würde die gewünschte Meldung erzeugt werden.

Vielen Dank.

Wolfgang

**Comment by Ma7h1** [comment]
Hallo,

das ist nicht Korrekt,

`Python 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import configparser
>>> config = configparser.ConfigParser()
>>> config.read("test_file_not_there")
[]`

Ich habe aber noch eine Zeile eingebaut, wenn da keine Konfigurationssections sind, dass er dann abbricht.
-> wird in der nächsten Version drin sein

Gruß
Mathias
